---
title: "my_tidying"
author: "Dave Parkin"
date: "07/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#install.packages("janitor")
library(janitor)
library(here)
library(readxl)
```

```{r read in data}
inverts <- read_excel(here("data", "inverts.xlsx"))
```

```{r longer pivot}
inverts_long <- pivot_longer(data = inverts,
                             cols = '2016':'2018',
                             names_to = 'year',
                             values_to = 'sp_count')
```

```{r explore class of new observation column}
class(inverts_long$year)
```

```{r mutate (coerce) class character to numeric}
inverts_long <- inverts_long %>%
  mutate(year = as.numeric(year))
```

```{r explore class of coerced observation column}
class(inverts_long$year)
```

```{r long to wide pivot}
inverts_wide <- inverts_long %>%
  pivot_wider(names_from = common_name,
              values_from = sp_count)
```

```{r clean header names}
inverts_wide<- inverts_wide %>%
  clean_names("upper_camel")

names(inverts_wide)
```

```{r concantenate}
inverts_unite <- inverts_long %>%
  unite(col = "site_year",
              c(site,year),
              sep = "_")
```

```{r concat activity}
inverts_unite2 <- inverts_long %>%
  unite(col = "mo_yr",
              c(month,year),
              sep = "hello!")
```

```{r concantenate3}
inverts_triple_unite <- inverts_long %>%
  unite(col = "year_site_name",
              c(year,site,common_name),
              sep = "-")

head(inverts_triple_unite)
```

```{r split cells (seperate)}
inverts_sep <- inverts_unite %>%
  tidyr::separate(site_year, into = c("my_site", "my_year"))
```

```{r find and replace}
ca_abbr <- inverts %>%
  mutate(
    common_name = 
      str_replace(common_name,
                  pattern = "california",
                  replacement = "CA")
  )
```