---
title: "pivot_lobsters"
author: "Dave Parkin"
date: "05/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
#install.packages("skimr")
library(skimr)
#install.packages("kableExtra")
library(kableExtra)
```

## read in data
```{r import xlsx}
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)
```

# explore data
```{r skim summary}
skimr::skim(lobsters)
```
```{r dplyr pivot equivilent}
lobsters  %>%
  group_by(year) %>%
  summarize(count_by_year = n())
```

```{r dplyr pivot no grp}
lobsters %>%
  summarise(count = n())
```

```{r r dplyr pivot grp only}
lobsters %>%
  group_by(year)
```

```{r dplyr pivot 2 groups}
lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_year = n())
```

```{r dplyr pivot 2 groups multiple variables}
lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm))
```

```{r dplyr pivot 2 groups multiple variables exc NAs}
lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_year = n(),
            mean_size_mm = mean(size_mm, na.rm = TRUE))
```

```{r dplyr pivot 2 groups multiple variables exc NAs2}
lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_year = n(),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_nm = sd(size_mm, na.rm = TRUE))
```

```{r dplyr pivot 2 groups multiple variables exc NAs as variable}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_year = n(),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_nm = sd(size_mm, na.rm = TRUE))
```

There are `r nrow(lobsters)` total lobsters included in this report.

```{r table formatting}
siteyear_summary %>%
  kable(format = "html", digits = 2, caption = "Lobsters by Site and Year")
```
```{r 6.4.6 activity median}
site_year_summary2 <- lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_year = n(),
            median_size_mm = median(size_mm,na.rm = TRUE),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_nm = sd(size_mm, na.rm = TRUE))
```

```{r 6.4.6 activity plot}
ggplot(site_year_summary2, aes(x = year, y =median_size_mm, colour = site)) +
  geom_line()
```
```{r ggsave}
ggsave(here("figures", "lobsters-line2.png"))
```

```{r 6.4.6 activity plot2}
ggplot(site_year_summary2, aes(x=year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)
```

```{r ggsave2}
ggsave(here("figures", "lobsters-facet2.png"))
```

##Using count() instead nrow(). 

There are `r count(lobsters)` total lobsters included in this summary.

```{r mutate add column}
lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000,
         millenia = 2000,
         observer = "Allison Horst")
```

```{r select columns}
lobsters_detailed %>%
  select(date, site, size_m)
```