---
title: "Creating graphs in R with 'ggplot2'"
author: "Dave Parkin"
date: "30/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
```

# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.

```{r read-csv}
ca_np <- read.csv(here("data", "ca_np.csv"))
```

``` {r read-xls(x)}
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r ggplots}
ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_line()
```

```{r aes_var}
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))
```

```{r point}
gg_base +
  geom_point()
```

``` {r col}
gg_base +
  geom_col()
```

```{r area}
gg_base +
  geom_area()
```

```{r custom line}
gg_base +
  geom_line(
    colour = "purple",
    linetype = "dashed"
  )
```

``` {r custom point}
gg_base +
  geom_point(colour = "purple",
             pch = 17,
             size = 4,
             alpha = 0.5)
```

``` {r custom element point}
gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    alpha = 0.5
  )
```

```{r custom element col}
gg_base +
  geom_col(aes(fill = visitors))
```

``` {r custom element point theme1}
gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    alpha = 0.5
  ) +
  theme_light()
```

``` {r custom element point theme2}
gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    alpha = 0.5
  ) +
  theme_minimal()
```

``` {r custom element point theme3}
gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    alpha = 0.5
  ) +
  theme_linedraw()
```

``` {r line dotted theme labels}
gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )
```

``` {r combine geoms (chart types)}
gg_base +
  geom_line(colour = "purple") +
  geom_point(colour = "orange",
             aes(size = year),
             alpha = 0.5)
```

```{r col and line}
gg_base +
  geom_col(fill = "orange",
           colour = "purple") +
  geom_line(colour = "green")
```

```{r multi-series}
ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name, colour = park_name)) +
  geom_line()
```

```{r ggplot stored}
gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))
```

#```{r facet (multiple chart by list value (region?))}
#gg_np +
 # geom_line(show.legend = FALSE) +
  #theme_light() +
  #labs(X = "year", y = "annual visitors") +
  #facet_wrap(~ park_name)
#```

#```{r export with ggsave}
#ggsave(here("figures", "np_graph3.jpg"), dpi = 180, width = 8, height = 7)
#```